global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # - job_name: 'otel-collector'
  #   static_configs:
  #     - targets: ['otel-collector:8889']  # Métricas do OTel
      
  - job_name: 'servicebus-sender'
    static_configs:
      - targets: ['host.docker.internal:5230']
      
  - job_name: 'ServiceBusWorker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9464']

  - job_name: 'alloy'
    # Configuração para raspar as métricas internas do Alloy
    # Use a porta 12345, conforme definido no seu compose e no alloy-config.alloy
    static_configs:
      - targets: ['alloy:12345']
        labels:
          instance: alloy_agent